### ISSUE TITLE
Streamlining

### ISSUE THREAD

**Issue by tyleransom** [wschpero/statastates#1]
This is a great program, and I just used it for the first time. Worked like a charm! Thanks for putting it out there.

I have a couple of points of feedback, which you should feel free to ignore:

1. On the [merge lines](https://github.com/wschpero/statastates/blob/master/statastates.ado#L32) of `statastates.ado`, perhaps consider adding the `nogen` option so that there isn't a `_merge` variable in the dataset?

2. Does this program work if there already exists a `_merge` variable in the master data set?

**Comment by wschpero** [comment]
Thanks for the feedback — I'm glad you found the program useful. It's admittedly somewhat inelegant at the moment, so suggestions welcome!

I think I originally elected not to include `nogen` so that users would be able to easily / transparently troubleshoot any merge issues using `_merge`. That certainly results in a few tradeoffs from a usability standpoint like the one you mention (`_merge` can't be in the dataset prior to use of the command).

One alternative would be to add `nogen` with ` keep(match master)`. Users would still be able to identify issues using the `merge` report, although they wouldn't be able to leverage `_merge` to make any subsequent changes. Is this preferable from your standpoint?

Thanks again!

Best,
Will

**Comment by tyleransom** [comment]
Thanks for getting back to me, Will. I think that adding `nogen` with `keep(match master)` seems like a good plan.

The other suggestion I had was to do something like `capture drop _merge` at the top of the ado file in case someone has a lingering `_merge` variable. I haven't tested that functionality, though, so I may be missing something.

Cheers,
Tyler

**Comment by wschpero** [comment]
Hi Tyler,

I've attempted to implement your suggestion with a new option, `nogen`. Specifying `nogen` should suppress creation of `_merge` and limit the dataset to matched and unmatched master observations. It can be downloaded here:

```
net install statastates, from(https://raw.github.com/wschpero/statastates/master/) replace
```

I haven't fully tested it yet -- please let me know if you encounter any issues. Once it's finalized I'll go ahead and submit an update to SSC.

Thanks again for reaching out!

Best,
Will

**Comment by tyleransom** [comment]
Hi Will,

Thanks for this: I have tested it and found it to work well with the new option. I appreciate your attention to this!

Cheers,
Tyler

**Comment by wschpero** [comment]
Thanks for the suggestion, Tyler!

Best,
Will
