### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by enwakpuda** [wschpero/statastates#9]
Hi, I am working with data that has state name spelled out and want state abbreviations.

I simply followed the instructions for using statastates but got and error message. 

After typing "ssc install statastates" and the installation was complete, I typed "statastates name(state)" and got the following error:
file .....Documents/Stata/ado/personal/statastates_data/statastates.dta not found

Why am I getting this error? I thought the statastates.dta would already be included in the statastates package.

Thank you for any help with this.

Emily

**Comment by wschpero** [comment]
Hi Emily,

The first time the package is run, it must create and save a dta file with the state name / code information. People seem to get this error if their Stata program does not have read-write privileges for the relevant directory. Once you fix those permissions, you should be all set!

Otherwise, you can change the directory used for personal ado files to a path where you know permissions are ok. See https://kb.iu.edu/d/arur

I'm going to close this issue, but feel free to email if you have any other questions!

Best,
Will

**Comment by enwakpuda** [comment]
Thank you that worked.
